export const formattedCO2 = () => (
    <span>
        CO<sub>2</sub>
    </span>
);

export const formatElementWithCO2 = (str) => {
    if (str && str.includes("CO2")) {
        return (
            <span
                dangerouslySetInnerHTML={{
                    __html: str.replace("CO2", "CO<sub>2</sub>"),
                }}
            ></span>
        );
    } else {
        return str;
    }
};

export const getCarbonIntensityDesc = () => (
    <>
        The amount of the carbon dioxide ({formattedCO2()}) released to produce a kilowatt hour (kWh) of electricity.
        The higher the number, the less environmentally friendly it is.
    </>
);

export const getCarbonBenefitsDesc = (maxInstallation) => (
    <>
        The amount of the carbon dioxide ({formattedCO2()}) emissions that can be avoided by maximising the installation
        of solar panels ({maxInstallation}).
    </>
);

export const getElecAvailabilityDesc = (maxInstallation, chartLabel = "") => (
    <>
        The total amount of the electricity that can be generated by maximising the installation of solar panels (
        {maxInstallation}){chartLabel}.
    </>
);

export const getPVOUTDesc = () => (
    <>
        Potential solar power(PVOUT) is used to estimate the amount of energy a solar panel can produce in a specific
        location.
    </>
);

export const getTPPOUTDesc = () =>
    "Total Solar/Photovoltaic Power Output (TPPOUT) refers to the total amount of electricity produced by a solar panel or a solar panel system over a given period of time.";

export const getSolarPowerGenerationDesc = () => "Current percentage of electricity generated by solar power";
